name: maco
description: An anime downloading cli based on libanime.
version: 0.0.1
homepage: https://github.com/libanime/maco/
repository: https://github.com/libanime/maco/
issue_tracker: https://github.com/libanime/maco/issues
funding:
 - https://boosty.to/libanime
topics:
  - parse
  - http
  - network
  - anime
  - cli
  - downloader
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  libanime: ^0.0.8
  mason_logger: ^0.2.5
  path_provider: ^2.1.1
  platform: ^3.1.3
  pub_updater: ">=0.3.1 <0.5.0"

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^5.1.0

executables:
  maco:
