name: maco
description: An beautiful looking anime downloading cli based on libanime.
version: 0.0.4
homepage: https://github.com/libanime/maco/
repository: https://github.com/libanime/maco/
issue_tracker: https://github.com/libanime/maco/issues
funding:
 - https://boosty.to/libanime
topics:
  - parse
  - network
  - anime
  - cli
  - downloader
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  cli_completion: ">=0.3.0 <0.6.0"
  dio: ^5.4.0
  libanime: ^0.1.0
  mason_logger: ^0.2.10
  pub_updater: ^0.3.1

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^5.1.0

executables:
  maco:
